import type { BaseRootCauseRule } from '../types';

export const TEMU_ROOT_CAUSE_RULES = [
  {
    platform: 'TEMU',
    ruleCode: 'R001',
    ruleName: '访客数下降',
    primaryAnomalyType: 'traffic_drop',
    priority: 80,
    coreProblem: '店铺进入流量减少',
    businessMeaning: '店铺访客规模下降，后续存在销售额下滑风险。',
    coreAttribution: '曝光减少 / 商品权重下降',
    possibleReasons: ['平台自然流量下降', '商品权重下降', '活动结束', '价格竞争力下降'],
    recommendedActions: ['检查主推商品访客变化', '检查活动是否结束', '对比其他店铺是否同步下降', '优先恢复高流量商品曝光'],
    shouldCreateTask: true,
    bossAttentionRequired: true,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R002',
    ruleName: '浏览量下降',
    primaryAnomalyType: 'traffic_quality_issue',
    priority: 60,
    coreProblem: '用户浏览深度下降',
    businessMeaning: '用户进入后浏览次数减少，后续可能影响成交。',
    coreAttribution: '商品吸引力下降 / 商品结构问题',
    possibleReasons: ['商品吸引力下降', '商品结构不合理', '主推商品承接弱', '价格吸引力下降'],
    recommendedActions: ['检查人均浏览量', '优化商品排序', '检查高访客低浏览商品', '优化主图和价格'],
    shouldCreateTask: true,
    bossAttentionRequired: false,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R003',
    ruleName: '支付买家数下降',
    primaryAnomalyType: 'transaction_decline',
    priority: 85,
    coreProblem: '实际成交人数下降',
    businessMeaning: '支付买家数下降说明成交能力明显变差。',
    coreAttribution: '流量下降或转化恶化',
    possibleReasons: ['访客下降', '转化率下降', '商品价格竞争力下降', '活动结束'],
    recommendedActions: ['判断是流量问题还是转化问题', '优先恢复成交能力', '排查主推成交商品', '检查活动和价格变化'],
    shouldCreateTask: true,
    bossAttentionRequired: true,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R004',
    ruleName: '支付转化率下降',
    primaryAnomalyType: 'conversion_drop',
    priority: 90,
    coreProblem: '流量变现能力下降',
    businessMeaning: '访客无法有效转化为买家，是经营质量恶化的重要信号。',
    coreAttribution: '价格竞争力下降 / 商品吸引力下降',
    possibleReasons: ['竞品降价', '商品吸引力下降', '主图详情弱', '评价售后影响转化'],
    recommendedActions: ['检查高访客低转化商品', '对比竞品价格', '优化主图、标题和卖点', '必要时调整优惠'],
    shouldCreateTask: true,
    bossAttentionRequired: true,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R005',
    ruleName: '支付件数下降',
    primaryAnomalyType: 'transaction_decline',
    priority: 65,
    coreProblem: '商品成交件数减少',
    businessMeaning: '支付件数下降说明商品销售规模缩小。',
    coreAttribution: '多件购买减少 / 买家减少',
    possibleReasons: ['买家减少', '多件购买下降', '组合商品吸引力下降', '主推商品成交减少'],
    recommendedActions: ['检查件单量', '优化组合商品', '提升多件购买场景', '检查主推商品成交'],
    shouldCreateTask: true,
    bossAttentionRequired: false,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R006',
    ruleName: '销售额下降',
    primaryAnomalyType: 'sales_decline',
    priority: 95,
    coreProblem: '店铺整体经营结果下降',
    businessMeaning: '销售额下降说明整体经营结果恶化，需要拆解流量、转化、件数和客单问题。',
    coreAttribution: '流量、转化、件数或客单至少一个恶化',
    possibleReasons: ['流量下降', '转化下降', '件单量下降', '客单价下降'],
    recommendedActions: ['拆解销售额下降来源', '找出下降最大的店铺或商品', '优先处理高影响问题', '跟踪恢复效果'],
    shouldCreateTask: true,
    bossAttentionRequired: true,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R007',
    ruleName: '访客下降但转化稳定',
    primaryAnomalyType: 'traffic_drop',
    priority: 78,
    coreProblem: '流量规模下降但成交效率稳定',
    businessMeaning: '成交效率未明显恶化，销售压力主要来自流量规模减少。',
    coreAttribution: '流量入口减少',
    possibleReasons: ['自然流量下降', '活动资源减少', '商品曝光下降', '价格竞争力下降'],
    recommendedActions: ['不要优先改详情页', '优先恢复商品曝光和访客', '检查活动和价格状态', '扩大高转化商品流量'],
    shouldCreateTask: true,
    bossAttentionRequired: false,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R008',
    ruleName: '访客稳定但转化下降',
    primaryAnomalyType: 'conversion_drop',
    priority: 88,
    coreProblem: '流量承接效率下降',
    businessMeaning: '流量规模尚可，但商品承接或购买决策效率下降。',
    coreAttribution: '转化链路恶化',
    possibleReasons: ['价格优势减弱', '商品卖点不清晰', '评价或售后影响', '优惠力度不足'],
    recommendedActions: ['优先检查价格和竞品', '优化高访客低转化商品', '调整主图、标题和卖点', '必要时调整优惠或活动'],
    shouldCreateTask: true,
    bossAttentionRequired: true,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R009',
    ruleName: '浏览量上升但转化下降',
    primaryAnomalyType: 'traffic_quality_issue',
    priority: 75,
    coreProblem: '浏览增长未形成有效成交',
    businessMeaning: '曝光或浏览增加但成交效率变差，可能存在流量质量或商品承接问题。',
    coreAttribution: '流量质量下降 / 商品承接不足',
    possibleReasons: ['低意向流量增加', '商品详情承接弱', '价格或定制说明影响决策', '礼品属性表达不足'],
    recommendedActions: ['优化高浏览低成交商品', '检查价格和定制说明', '强化礼品属性和核心卖点', '降低购买决策成本'],
    shouldCreateTask: true,
    bossAttentionRequired: false,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R010',
    ruleName: '访客上升但买家不升',
    primaryAnomalyType: 'conversion_drop',
    priority: 76,
    coreProblem: '新增访客未转化为买家',
    businessMeaning: '新增流量未有效转化为买家，需要关注流量质量和转化链路。',
    coreAttribution: '新增流量质量不足 / 购买承接不足',
    possibleReasons: ['新增访客来源不准', '主图吸引错人群', '价格吸引力不足', '高访客商品转化弱'],
    recommendedActions: ['不盲目继续放大流量', '检查新增访客来源和转化率', '优化高访客低买家商品', '检查主图是否吸引错人群'],
    shouldCreateTask: true,
    bossAttentionRequired: false,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R011',
    ruleName: '买家数下降且销售额下降',
    primaryAnomalyType: 'transaction_decline',
    priority: 92,
    coreProblem: '成交人群和销售规模同步下降',
    businessMeaning: '成交人群减少并带动销售额下滑，是高优先级经营风险。',
    coreAttribution: '成交能力下降',
    possibleReasons: ['有效成交流量减少', '主推成交商品走弱', '活动结束', '价格变化影响购买'],
    recommendedActions: ['同时拆解访客和转化变化', '优先排查主推成交商品', '检查活动结束和价格变化', '对下降最大的店铺生成任务'],
    shouldCreateTask: true,
    bossAttentionRequired: true,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R012',
    ruleName: '支付件数上升但销售额下降',
    primaryAnomalyType: 'customer_unit_price_drop',
    priority: 72,
    coreProblem: '成交结构偏向低价商品',
    businessMeaning: '销量件数提升但销售额下降，可能存在均价下降或低价商品占比提升。',
    coreAttribution: '件均价或客单价下降',
    possibleReasons: ['低价商品占比提升', '促销降价影响销售额', '高客单商品曝光不足', '商品结构失衡'],
    recommendedActions: ['检查件均价和客单价', '提升高客单商品曝光', '控制低价引流商品比例', '优化商品结构'],
    shouldCreateTask: true,
    bossAttentionRequired: false,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R013',
    ruleName: '销售额下降但转化率上升',
    primaryAnomalyType: 'traffic_drop',
    priority: 74,
    coreProblem: '成交效率改善但流量或客单不足',
    businessMeaning: '成交效率改善但销售额仍下降，需关注流量规模、买家数或客单变化。',
    coreAttribution: '流量下降或客单下降',
    possibleReasons: ['访客规模下降', '高转化商品流量不足', '客单价下降', '件单价下降'],
    recommendedActions: ['不要误判为整体经营变好', '优先恢复访客和曝光', '扩大高转化商品流量', '检查流量下降来源'],
    shouldCreateTask: true,
    bossAttentionRequired: false,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R014',
    ruleName: '销售额下降且访客下降',
    primaryAnomalyType: 'traffic_drop',
    priority: 90,
    coreProblem: '流量下降带动销售额下降',
    businessMeaning: '销售额下滑与访客减少同步出现，流量端可能是核心影响因素。',
    coreAttribution: '流量端衰退',
    possibleReasons: ['平台分发减少', '主推商品流量下滑', '活动资源结束', '商品权重下降'],
    recommendedActions: ['优先恢复访客', '检查主推商品流量', '对比其他店铺是否同步下降', '不要优先改转化承接'],
    shouldCreateTask: true,
    bossAttentionRequired: true,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R015',
    ruleName: '销售额下降且转化下降',
    primaryAnomalyType: 'conversion_drop',
    priority: 94,
    coreProblem: '转化效率下降带动销售额下降',
    businessMeaning: '销售额和成交效率同步下滑，需优先排查商品、价格和转化链路。',
    coreAttribution: '转化能力恶化',
    possibleReasons: ['商品竞争力不足', '竞品价格冲击', '主图标题卖点弱', '优惠或价格策略不足'],
    recommendedActions: ['优先处理高访客低转化商品', '对比竞品价格', '优化主图、标题、卖点', '必要时调整优惠或价格策略'],
    shouldCreateTask: true,
    bossAttentionRequired: true,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R016',
    ruleName: '访客稳定但浏览量下降',
    primaryAnomalyType: 'traffic_quality_issue',
    priority: 58,
    coreProblem: '访客浏览深度下降',
    businessMeaning: '人均浏览深度下降，可能影响商品发现和后续成交。',
    coreAttribution: '商品吸引力或展示结构下降',
    possibleReasons: ['主推商品排序不佳', '商品图片吸引力下降', '商品价格竞争力下降', '展示商品不足'],
    recommendedActions: ['检查人均浏览量', '优化主推商品排序和图片', '增加更有吸引力的商品展示', '检查商品价格竞争力'],
    shouldCreateTask: true,
    bossAttentionRequired: false,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R017',
    ruleName: '浏览量上升但买家下降',
    primaryAnomalyType: 'traffic_quality_issue',
    priority: 82,
    coreProblem: '浏览增长但成交买家减少',
    businessMeaning: '浏览热度未转化为成交买家，可能存在购买意愿或商品竞争力问题。',
    coreAttribution: '高浏览商品成交承接弱',
    possibleReasons: ['无效浏览增加', '详情页或定制说明不清晰', '竞品价格更优', '信任感和场景表达不足'],
    recommendedActions: ['优先优化高浏览低买家商品', '检查详情页和定制说明', '对比竞品价格', '强化信任感和礼品场景'],
    shouldCreateTask: true,
    bossAttentionRequired: false,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R018',
    ruleName: '买家稳定但支付件数下降',
    primaryAnomalyType: 'customer_unit_price_drop',
    priority: 62,
    coreProblem: '单买家购买件数减少',
    businessMeaning: '买家规模稳定但件单减少，可能存在连带购买或单次购买数量下降。',
    coreAttribution: '件单量下降',
    possibleReasons: ['连带购买减少', '组合款吸引力下降', '多件购买场景不足', '热销多件商品缺货'],
    recommendedActions: ['检查件单量是否下降', '优化组合款和多件购买商品', '增加多件购买场景', '提升组合商品曝光'],
    shouldCreateTask: true,
    bossAttentionRequired: false,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R019',
    ruleName: '销售额上升但转化下降',
    primaryAnomalyType: 'risk_fluctuation',
    priority: 55,
    coreProblem: '销售增长中存在转化效率下滑',
    businessMeaning: '销售额增长中存在转化效率下滑信号，需关注增长质量。',
    coreAttribution: '增长质量存在波动风险',
    possibleReasons: ['高客单订单拉动销售额', '新增流量质量偏低', '高访客商品转化弱', '销售增长不可持续'],
    recommendedActions: ['不要只看销售额增长', '继续观察转化率', '优化高访客低转化商品', '防止后续销售回落'],
    shouldCreateTask: false,
    bossAttentionRequired: false,
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R020',
    ruleName: '访客、买家、销售额同步下降',
    primaryAnomalyType: 'sales_decline',
    priority: 100,
    coreProblem: '店铺整体经营恶化',
    businessMeaning: '访客、买家和销售额同步下降，说明从流量到成交都出现明显恶化。',
    coreAttribution: '流量 + 转化双重恶化',
    possibleReasons: ['店铺整体流量衰退', '主推商品失去权重', '价格竞争力下降', '活动结束或竞品冲击'],
    recommendedActions: ['立即拆解流量和转化问题', '优先排查主推商品', '检查活动、价格、可售状态', '必须生成运营任务并跟踪恢复'],
    shouldCreateTask: true,
    bossAttentionRequired: true,
    enabled: true,
  },
] satisfies BaseRootCauseRule[];
