export default {
  apps: [
    {
      name: 'ecommerce-ops-system',
      script: 'npm',
      args: 'run start',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || '3000',
        AI_PROVIDER: process.env.AI_PROVIDER || 'mock',
        OPENAI_API_KEY: process.env.OPENAI_API_KEY || '',
        DATA_DIR: process.env.DATA_DIR || './data',
        DATABASE_PATH: process.env.DATABASE_PATH || './data/database.sqlite',
        DATABASE_URL: process.env.DATABASE_URL || '',
        DATABASE_SSL: process.env.DATABASE_SSL || '',
        BACKUP_DIR: process.env.BACKUP_DIR || './data/backup',
        BACKUP_1688_DIR: process.env.BACKUP_1688_DIR || '',
        UPLOADS_1688_DIR: process.env.UPLOADS_1688_DIR || '',
        PG_DUMP_PATH: process.env.PG_DUMP_PATH || '',
        SESSION_SECRET: process.env.SESSION_SECRET || '',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || '3000',
        AI_PROVIDER: process.env.AI_PROVIDER || 'mock',
        OPENAI_API_KEY: process.env.OPENAI_API_KEY || '',
        DATA_DIR: process.env.DATA_DIR || './data',
        DATABASE_PATH: process.env.DATABASE_PATH || './data/database.sqlite',
        DATABASE_URL: process.env.DATABASE_URL || '',
        DATABASE_SSL: process.env.DATABASE_SSL || '',
        BACKUP_DIR: process.env.BACKUP_DIR || './data/backup',
        BACKUP_1688_DIR: process.env.BACKUP_1688_DIR || '',
        UPLOADS_1688_DIR: process.env.UPLOADS_1688_DIR || '',
        PG_DUMP_PATH: process.env.PG_DUMP_PATH || '',
        SESSION_SECRET: process.env.SESSION_SECRET || '',
      },
    },
  ],
};
