import type { MetricRelation } from './metricRelationTypes';

export const metricRelationLibrary: MetricRelation[] = [
  {
    id: 'sales-amount-from-traffic-conversion-aov',
    name: '销售额关系',
    category: 'sales',
    type: 'formula',
    targetMetric: 'salesAmount',
    sourceMetrics: ['visitorCount', 'conversionRate', 'avgOrderValue'],
    formulaText: 'salesAmount = visitorCount × conversionRate × avgOrderValue',
    impactDescription: '访客数、转化率或客单价上升通常会带动销售额上升。',
    impactDirection: 'positive',
    explanation: '销售额由可触达流量、成交效率和单笔成交金额共同决定。',
  },
  {
    id: 'order-count-from-traffic-conversion',
    name: '订单数关系',
    category: 'sales',
    type: 'formula',
    targetMetric: 'orderCount',
    sourceMetrics: ['visitorCount', 'conversionRate'],
    formulaText: 'orderCount = visitorCount × conversionRate',
    impactDescription: '访客数或转化率上升通常会带动订单数上升。',
    impactDirection: 'positive',
    explanation: '订单数反映流量规模和流量成交效率的共同结果。',
  },
  {
    id: 'average-order-value-from-sales-orders',
    name: '客单价关系',
    category: 'sales',
    type: 'derived',
    targetMetric: 'avgOrderValue',
    sourceMetrics: ['salesAmount', 'orderCount'],
    formulaText: 'avgOrderValue = salesAmount ÷ orderCount',
    impactDescription: '销售额相对订单数越高，客单价越高。',
    impactDirection: 'neutral',
    explanation: '客单价用于衡量单笔订单的平均成交金额。',
  },
  {
    id: 'ctr-from-clicks-impressions',
    name: '点击率关系',
    category: 'traffic',
    type: 'derived',
    targetMetric: 'ctr',
    sourceMetrics: ['clickCount', 'impressionCount'],
    formulaText: 'ctr = clickCount ÷ impressionCount',
    impactDescription: '点击数相对曝光数越高，点击率越高。',
    impactDirection: 'positive',
    explanation: '点击率用于衡量曝光转化为点击的效率。',
  },
  {
    id: 'conversion-rate-from-orders-visitors',
    name: '转化率关系',
    category: 'conversion',
    type: 'derived',
    targetMetric: 'conversionRate',
    sourceMetrics: ['orderCount', 'visitorCount'],
    formulaText: 'conversionRate = orderCount ÷ visitorCount',
    impactDescription: '订单数相对访客数越高，转化率越高。',
    impactDirection: 'positive',
    explanation: '转化率用于衡量访客最终产生订单的效率。',
  },
  {
    id: 'visitor-count-from-impressions-ctr',
    name: '访客数关系',
    category: 'traffic',
    type: 'formula',
    targetMetric: 'visitorCount',
    sourceMetrics: ['impressionCount', 'ctr'],
    formulaText: 'visitorCount = impressionCount × ctr',
    impactDescription: '曝光数或点击率下降通常会导致访客数下降。',
    impactDirection: 'positive',
    explanation: '访客数可以由曝光规模和点击效率共同解释。',
  },
  {
    id: 'roas-from-sales-ad-spend',
    name: 'ROAS 关系',
    category: 'ad',
    type: 'derived',
    targetMetric: 'roas',
    sourceMetrics: ['salesAmount', 'adSpend'],
    formulaText: 'roas = salesAmount ÷ adSpend',
    impactDescription: '销售额相对广告花费越高，ROAS 越高。',
    impactDirection: 'positive',
    explanation: 'ROAS 用于衡量广告投入带来的销售回报效率。',
  },
  {
    id: 'refund-rate-from-refunds-sales',
    name: '退款率关系',
    category: 'afterSale',
    type: 'derived',
    targetMetric: 'refundRate',
    sourceMetrics: ['refundAmount', 'salesAmount'],
    formulaText: 'refundRate = refundAmount ÷ salesAmount',
    impactDescription: '退款金额相对销售额越高，退款率越高。',
    impactDirection: 'negative',
    explanation: '退款率用于衡量售后退款对经营结果的影响；refundAmount 当前作为预留标准指标。',
    optional: true,
    futureMetrics: ['refundAmount'],
  },
];
