import type { AnomalyCategory } from './anomalyRuleTypes';
import type { OperationSolution, SolutionActionType, SolutionPriority } from './solutionTypes';

function solution(
  id: string,
  causeKey: string,
  title: string,
  priority: SolutionPriority,
  actionType: SolutionActionType,
  description: string,
  checkSteps: string[],
  suggestedActions: string[],
  expectedEffect: string,
  applicableMetrics: string[],
  applicableCategories: AnomalyCategory[],
  causeAliases: string[] = [],
): OperationSolution {
  return {
    id,
    causeKey,
    causeAliases,
    title,
    priority,
    actionType,
    description,
    checkSteps,
    suggestedActions,
    expectedEffect,
    applicableMetrics,
    applicableCategories,
  };
}

export const solutionLibrary: OperationSolution[] = [
  solution(
    'visitor-count-decline-check',
    'visitorCount',
    '访客数下降排查',
    'high',
    'check',
    '用于排查访客数下降导致的销售额、订单数或转化表现异常。',
    ['检查近期曝光量是否同步下降', '检查点击率是否下降', '检查主推商品是否失去流量', '检查活动、广告或平台推荐是否变化'],
    ['优先恢复高流量商品曝光', '优化主图和标题，提高点击', '检查广告预算和活动状态', '对比近30天高流量商品表现'],
    '恢复有效访客规模，为销售额和订单数恢复提供流量基础。',
    ['visitorCount', 'salesAmount', 'orderCount', 'conversionRate'],
    ['traffic', 'sales', 'conversion'],
  ),
  solution(
    'impression-count-decline-check',
    'impressionCount',
    '曝光数下降排查',
    'high',
    'check',
    '用于定位流量入口变少、商品曝光减少导致的访客下降。',
    ['检查曝光量下降的商品范围', '检查活动、广告、搜索和推荐入口变化', '检查主推商品是否下架、断货或排名下降', '检查近30天曝光贡献最高商品'],
    ['恢复核心商品曝光入口', '补充活动和广告曝光', '优化标题、关键词和商品基础信息', '优先处理历史高曝光商品'],
    '提升商品可见性，改善访客数和后续成交机会。',
    ['impressionCount', 'visitorCount'],
    ['traffic'],
  ),
  solution(
    'ctr-decline-optimize',
    'ctr',
    '点击率下降优化',
    'medium',
    'optimize',
    '用于处理曝光存在但点击承接不足的问题。',
    ['检查主图点击吸引力', '检查标题是否表达核心卖点', '检查价格、优惠和评分是否影响点击', '对比点击率高低商品差异'],
    ['优化主图、标题和首屏卖点', '强化价格和优惠表达', '保留高点击素材并做对照测试', '减少低相关曝光入口'],
    '提高曝光到访客的转化效率，改善访客数。',
    ['ctr', 'clickCount', 'impressionCount', 'visitorCount'],
    ['traffic'],
  ),
  solution(
    'conversion-rate-low-optimize',
    'conversionRate',
    '转化率过低优化',
    'urgent',
    'optimize',
    '用于处理访客进入后没有有效下单的问题。',
    ['检查商品详情页与主图标题是否一致', '检查价格和优惠力度', '检查近7天评论和售后反馈', '检查库存和SKU可售状态', '对比同类商品转化表现'],
    ['优化详情页核心卖点和信任信息', '调整价格或优惠策略', '修复库存、规格和下单障碍', '优先优化高访客低转化商品'],
    '提升访客到订单的成交效率，带动订单数和销售额恢复。',
    ['conversionRate', 'orderCount', 'salesAmount'],
    ['conversion', 'sales'],
  ),
  solution(
    'average-order-value-decline-adjust',
    'avgOrderValue',
    '客单价下降调整',
    'medium',
    'adjust',
    '用于排查单笔成交金额下降对销售额的影响。',
    ['检查低价商品成交占比是否上升', '检查优惠力度是否过大', '检查套装、加购和搭配购买表现', '检查高客单商品是否断流或断货'],
    ['提升高客单商品曝光', '优化套装、组合和加购策略', '控制过度折扣', '恢复高客单商品库存和流量'],
    '改善单笔成交金额，提升销售额质量。',
    ['avgOrderValue', 'salesAmount', 'orderCount'],
    ['sales'],
  ),
  solution(
    'sales-amount-decline-check',
    'salesAmount',
    '销售额下降综合排查',
    'urgent',
    'check',
    '用于销售额下降时的总入口排查。',
    ['检查访客数、转化率和客单价是否同步变化', '检查核心商品销售贡献变化', '检查活动、广告、库存和价格变化', '检查异常是否集中在单店或单品'],
    ['优先定位影响最大的上游指标', '恢复主力商品流量和库存', '优化转化承接和价格策略', '持续监控恢复后的销售趋势'],
    '找到销售额下降的主因，并优先恢复最大影响项。',
    ['salesAmount', 'visitorCount', 'conversionRate', 'avgOrderValue'],
    ['sales'],
  ),
  solution(
    'order-count-decline-check',
    'orderCount',
    '订单数下降排查',
    'high',
    'check',
    '用于处理订单量下降引发的销售或转化异常。',
    ['检查访客数是否下降', '检查转化率是否下降', '检查库存和SKU是否影响下单', '检查主要成交商品是否异常'],
    ['恢复有效流量', '修复影响下单的库存和规格问题', '优化价格和优惠力度', '重点维护高成交商品'],
    '恢复订单规模，改善销售额和转化表现。',
    ['orderCount', 'visitorCount', 'conversionRate', 'salesAmount'],
    ['sales', 'conversion'],
  ),
  solution(
    'ad-spend-increase-check',
    'adSpend',
    '广告花费上升排查',
    'high',
    'check',
    '用于排查广告花费上升但回报不足导致的效率下降。',
    ['检查近7天广告花费变化', '检查广告带来的销售额是否同步增长', '检查低转化商品是否消耗预算', '检查投放结构和预算分配变化'],
    ['收紧低回报投放', '把预算转向高转化商品', '设置花费和ROAS监控阈值', '优化投放素材和人群'],
    '降低无效花费，提高广告投入回报。',
    ['adSpend', 'roas', 'salesAmount'],
    ['ad', 'sales'],
  ),
  solution(
    'roas-decline-check',
    'roas',
    'ROAS 下降排查',
    'high',
    'check',
    '用于定位广告回报下降的销售和花费原因。',
    ['检查销售额是否下降', '检查广告花费是否上升', '检查广告商品转化率', '检查预算是否流向低回报商品'],
    ['优化预算分配', '暂停低回报投放', '提升广告承接页转化', '优先投放高毛利和高转化商品'],
    '提升广告效率，减少花费浪费。',
    ['roas', 'adSpend', 'salesAmount', 'conversionRate'],
    ['ad'],
  ),
  solution(
    'refund-rate-increase-check',
    'refundRate',
    '退款率上升排查',
    'high',
    'check',
    '用于排查退款率上升对售后和经营质量的影响。',
    ['检查退款率是否集中在特定商品', '检查退款原因和售后反馈', '检查商品描述、质量和履约体验', '检查销售额下降是否放大退款率'],
    ['优先处理高退款商品', '修正商品描述和预期管理', '改善履约与售后体验', '建立退款原因监控'],
    '降低售后损耗，改善经营质量。',
    ['refundRate', 'refundAmount', 'salesAmount'],
    ['afterSale'],
  ),
  solution(
    'product-attractiveness-optimize',
    '商品吸引力不足',
    '商品吸引力优化',
    'high',
    'optimize',
    '用于处理商品卖点、评价、展示或竞争力不足导致的转化问题。',
    ['检查商品核心卖点是否清晰', '检查评价、评分和买家反馈', '检查同类商品卖点差异', '检查主图、标题和详情页表达'],
    ['强化核心卖点和信任信息', '优化商品内容表达', '补充评价和使用场景信息', '对低吸引力商品做替换或降权'],
    '提升用户购买意愿，改善转化率和订单数。',
    ['conversionRate', 'orderCount', 'salesAmount'],
    ['conversion', 'sales'],
    ['productAttractiveness'],
  ),
  solution(
    'price-competitiveness-adjust',
    '价格竞争力不足',
    '价格竞争力调整',
    'high',
    'adjust',
    '用于处理价格、优惠或竞品变化导致的转化压力。',
    ['检查当前价格与同类商品差距', '检查优惠力度和到手价', '检查价格调整后转化变化', '检查高流量低转化商品价格表现'],
    ['调整价格或优惠策略', '突出价格优势和组合价值', '对高流量商品优先做价格测试', '避免无差异低价竞争'],
    '降低购买决策阻力，提高转化率。',
    ['conversionRate', 'avgOrderValue', 'salesAmount'],
    ['conversion', 'sales'],
    ['priceCompetitiveness'],
  ),
  solution(
    'detail-page-material-fit-optimize',
    '详情页/素材承接不足',
    '详情页和素材承接优化',
    'medium',
    'optimize',
    '用于处理用户点击后详情页或素材没有有效承接购买意图的问题。',
    ['检查主图、标题和详情页信息是否一致', '检查详情页首屏是否回答核心疑问', '检查素材吸引的人群是否精准', '检查高跳失或低转化商品内容'],
    ['优化详情页首屏卖点', '统一素材和商品详情表达', '补充规格、场景和信任信息', '减少误导性素材带来的低质访客'],
    '提升流量承接效率，改善转化率。',
    ['conversionRate', 'visitorCount', 'orderCount'],
    ['conversion'],
    ['detailPageMaterialFit'],
  ),
  solution(
    'product-quality-escalate',
    '商品质量问题',
    '商品质量问题处理',
    'urgent',
    'escalate',
    '用于处理商品质量、描述不一致或预期偏差导致的售后异常。',
    ['检查退款和差评是否集中在质量问题', '检查批次、供应和包装是否异常', '检查商品描述是否夸大或不准确', '检查高退款商品的售后记录'],
    ['暂停或降低问题商品流量', '复核供应和质检环节', '修正商品描述和图片', '对高风险商品升级处理'],
    '减少质量相关退款和差评，控制售后风险。',
    ['refundRate', 'refundAmount'],
    ['afterSale'],
    ['productQualityIssue'],
  ),
  solution(
    'fulfillment-experience-monitor',
    '履约体验问题',
    '履约体验问题处理',
    'high',
    'monitor',
    '用于处理发货、物流、包装或售后响应影响退款率的问题。',
    ['检查履约时效是否变慢', '检查物流异常和包装反馈', '检查售后响应和处理时长', '检查退款原因是否集中在履约体验'],
    ['优化发货和物流协同', '改进包装和售后响应', '对异常履约链路设置监控', '优先处理高退款履约问题'],
    '改善履约体验，降低售后退款风险。',
    ['refundRate', 'refundAmount'],
    ['afterSale'],
    ['fulfillmentExperienceIssue'],
  ),
];
