import type { BaseReasonTree } from '../types';

export const TEMU_REASON_TREES = [
  {
    platform: 'TEMU',
    ruleCode: 'R001',
    ruleName: '访客数下降',
    primaryAnomalyType: 'traffic_drop',
    coreProblem: '店铺进入流量减少',
    businessMeaning: '店铺访客规模下降，后续存在销售额下滑风险。',
    possibleReasons: [
      { reasonCode: 'TRAFFIC_001', reasonName: '平台自然流量下降', confidence: 'high', evidenceNeeded: ['其他店铺访客趋势', '平台整体波动'], needHumanCheck: false },
      { reasonCode: 'TRAFFIC_002', reasonName: '商品权重下降', confidence: 'high', evidenceNeeded: ['主推商品访客变化', '商品曝光变化'], needHumanCheck: true },
      { reasonCode: 'TRAFFIC_003', reasonName: '活动结束', confidence: 'medium', evidenceNeeded: ['活动时间', '活动流量变化'], needHumanCheck: true },
      { reasonCode: 'TRAFFIC_004', reasonName: '价格竞争力下降', confidence: 'medium', evidenceNeeded: ['竞品价格', '自身价格变化'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R002',
    ruleName: '浏览量下降',
    primaryAnomalyType: 'traffic_quality_issue',
    coreProblem: '商品浏览规模减少',
    businessMeaning: '商品曝光和浏览活跃度下降，可能影响后续访客与成交。',
    possibleReasons: [
      { reasonCode: 'TRAFFIC_005', reasonName: '商品曝光下降', confidence: 'high', evidenceNeeded: ['商品曝光变化', '浏览入口变化'], needHumanCheck: false },
      { reasonCode: 'TRAFFIC_006', reasonName: '商品点击吸引力下降', confidence: 'medium', evidenceNeeded: ['点击率变化', '主图标题变化'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R003',
    ruleName: '支付买家数下降',
    primaryAnomalyType: 'transaction_decline',
    coreProblem: '成交买家规模减少',
    businessMeaning: '实际成交买家减少，销售规模存在直接下滑风险。',
    possibleReasons: [
      { reasonCode: 'TRANSACTION_001', reasonName: '有效流量减少', confidence: 'high', evidenceNeeded: ['访客变化', '转化率变化'], needHumanCheck: false },
      { reasonCode: 'TRANSACTION_002', reasonName: '购买决策阻力增加', confidence: 'medium', evidenceNeeded: ['价格变化', '评价变化'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R004',
    ruleName: '支付转化率下降',
    primaryAnomalyType: 'conversion_drop',
    coreProblem: '流量成交效率下降',
    businessMeaning: '流量成交效率下降，可能存在商品、价格或承接链路问题。',
    possibleReasons: [
      { reasonCode: 'CONVERSION_001', reasonName: '商品竞争力下降', confidence: 'high', evidenceNeeded: ['同类商品价格', '评价变化'], needHumanCheck: true },
      { reasonCode: 'CONVERSION_002', reasonName: '流量质量下降', confidence: 'medium', evidenceNeeded: ['访客来源', '浏览深度'], needHumanCheck: false },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R005',
    ruleName: '支付件数下降',
    primaryAnomalyType: 'transaction_decline',
    coreProblem: '成交商品件数减少',
    businessMeaning: '订单商品件数减少，可能影响整体销售额和库存周转。',
    possibleReasons: [
      { reasonCode: 'TRANSACTION_003', reasonName: '买家数量下降', confidence: 'high', evidenceNeeded: ['支付买家数变化'], needHumanCheck: false },
      { reasonCode: 'TRANSACTION_004', reasonName: '连带购买减少', confidence: 'medium', evidenceNeeded: ['件单变化', '组合商品表现'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R006',
    ruleName: '销售额下降',
    primaryAnomalyType: 'sales_decline',
    coreProblem: '店铺销售规模下降',
    businessMeaning: '店铺销售规模下降，需要优先定位流量、转化或客单问题。',
    possibleReasons: [
      { reasonCode: 'SALES_001', reasonName: '成交买家下降', confidence: 'high', evidenceNeeded: ['支付买家数变化'], needHumanCheck: false },
      { reasonCode: 'SALES_002', reasonName: '客单价下降', confidence: 'medium', evidenceNeeded: ['销售额变化', '支付件数变化'], needHumanCheck: false },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R007',
    ruleName: '访客下降但转化稳定',
    primaryAnomalyType: 'traffic_drop',
    coreProblem: '流量规模下降但成交效率稳定',
    businessMeaning: '成交效率未明显恶化，销售压力主要来自流量规模减少。',
    possibleReasons: [
      { reasonCode: 'TRAFFIC_007', reasonName: '自然流量入口减少', confidence: 'high', evidenceNeeded: ['访客来源变化'], needHumanCheck: false },
      { reasonCode: 'TRAFFIC_008', reasonName: '活动或推荐资源减少', confidence: 'medium', evidenceNeeded: ['活动档期', '资源位变化'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R008',
    ruleName: '访客稳定但转化下降',
    primaryAnomalyType: 'conversion_drop',
    coreProblem: '流量承接效率下降',
    businessMeaning: '流量规模尚可，但商品承接或购买决策效率下降。',
    possibleReasons: [
      { reasonCode: 'CONVERSION_003', reasonName: '商品价格优势减弱', confidence: 'high', evidenceNeeded: ['竞品价格', '自身价格变化'], needHumanCheck: true },
      { reasonCode: 'CONVERSION_004', reasonName: '商品评价或履约信号变弱', confidence: 'medium', evidenceNeeded: ['评价变化', '售后反馈'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R009',
    ruleName: '浏览量上升但转化下降',
    primaryAnomalyType: 'traffic_quality_issue',
    coreProblem: '浏览增长未形成有效成交',
    businessMeaning: '曝光或浏览增加但成交效率变差，可能存在流量质量或商品承接问题。',
    possibleReasons: [
      { reasonCode: 'TRAFFIC_009', reasonName: '低意向流量增加', confidence: 'high', evidenceNeeded: ['访客来源', '浏览深度'], needHumanCheck: false },
      { reasonCode: 'CONVERSION_005', reasonName: '商品详情承接不足', confidence: 'medium', evidenceNeeded: ['详情页变化', '加购变化'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R010',
    ruleName: '访客上升但买家不升',
    primaryAnomalyType: 'conversion_drop',
    coreProblem: '新增访客未转化为买家',
    businessMeaning: '新增流量未有效转化为买家，需要关注流量质量和转化链路。',
    possibleReasons: [
      { reasonCode: 'CONVERSION_006', reasonName: '新增流量购买意愿低', confidence: 'high', evidenceNeeded: ['访客来源变化', '支付转化率变化'], needHumanCheck: false },
      { reasonCode: 'CONVERSION_007', reasonName: '价格或优惠吸引力不足', confidence: 'medium', evidenceNeeded: ['优惠变化', '竞品价格'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R011',
    ruleName: '买家数下降且销售额下降',
    primaryAnomalyType: 'transaction_decline',
    coreProblem: '成交人群和销售规模同步下降',
    businessMeaning: '成交人群减少并带动销售额下滑，是高优先级经营风险。',
    possibleReasons: [
      { reasonCode: 'TRANSACTION_005', reasonName: '有效成交流量减少', confidence: 'high', evidenceNeeded: ['访客变化', '转化率变化'], needHumanCheck: false },
      { reasonCode: 'SALES_003', reasonName: '核心商品成交走弱', confidence: 'high', evidenceNeeded: ['主推商品销售额', '主推商品买家数'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R012',
    ruleName: '支付件数上升但销售额下降',
    primaryAnomalyType: 'customer_unit_price_drop',
    coreProblem: '成交结构偏向低价商品',
    businessMeaning: '销量件数提升但销售额下降，可能存在均价下降或低价商品占比提升。',
    possibleReasons: [
      { reasonCode: 'PRICE_001', reasonName: '低价商品占比提升', confidence: 'high', evidenceNeeded: ['商品销售结构', '平均件单价'], needHumanCheck: false },
      { reasonCode: 'PRICE_002', reasonName: '促销降价影响销售额', confidence: 'medium', evidenceNeeded: ['促销记录', '价格变化'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R013',
    ruleName: '销售额下降但转化率上升',
    primaryAnomalyType: 'traffic_drop',
    coreProblem: '成交效率改善但流量或客单不足',
    businessMeaning: '成交效率改善但销售额仍下降，需关注流量规模、买家数或客单变化。',
    possibleReasons: [
      { reasonCode: 'TRAFFIC_010', reasonName: '访客规模下降', confidence: 'high', evidenceNeeded: ['访客数变化'], needHumanCheck: false },
      { reasonCode: 'PRICE_003', reasonName: '客单价或件单价下降', confidence: 'medium', evidenceNeeded: ['支付件数', '销售额结构'], needHumanCheck: false },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R014',
    ruleName: '销售额下降且访客下降',
    primaryAnomalyType: 'traffic_drop',
    coreProblem: '流量下降带动销售额下降',
    businessMeaning: '销售额下滑与访客减少同步出现，流量端可能是核心影响因素。',
    possibleReasons: [
      { reasonCode: 'TRAFFIC_011', reasonName: '平台分发减少', confidence: 'high', evidenceNeeded: ['曝光变化', '访客来源变化'], needHumanCheck: false },
      { reasonCode: 'TRAFFIC_012', reasonName: '主推商品流量下滑', confidence: 'high', evidenceNeeded: ['主推商品访客', '主推商品销售额'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R015',
    ruleName: '销售额下降且转化下降',
    primaryAnomalyType: 'conversion_drop',
    coreProblem: '转化效率下降带动销售额下降',
    businessMeaning: '销售额和成交效率同步下滑，需优先排查商品、价格和转化链路。',
    possibleReasons: [
      { reasonCode: 'CONVERSION_008', reasonName: '商品竞争力不足', confidence: 'high', evidenceNeeded: ['价格', '评价', '竞品表现'], needHumanCheck: true },
      { reasonCode: 'CONVERSION_009', reasonName: '流量承接链路异常', confidence: 'medium', evidenceNeeded: ['详情页变化', '库存状态'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R016',
    ruleName: '访客稳定但浏览量下降',
    primaryAnomalyType: 'traffic_quality_issue',
    coreProblem: '访客浏览深度下降',
    businessMeaning: '人均浏览深度下降，可能影响商品发现和后续成交。',
    possibleReasons: [
      { reasonCode: 'TRAFFIC_013', reasonName: '商品吸引力下降', confidence: 'medium', evidenceNeeded: ['人均浏览量', '商品点击变化'], needHumanCheck: true },
      { reasonCode: 'TRAFFIC_014', reasonName: '流量需求不匹配', confidence: 'medium', evidenceNeeded: ['访客来源', '跳出表现'], needHumanCheck: false },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R017',
    ruleName: '浏览量上升但买家下降',
    primaryAnomalyType: 'traffic_quality_issue',
    coreProblem: '浏览增长未转化为成交买家',
    businessMeaning: '浏览热度未转化为成交买家，可能存在购买意愿或商品竞争力问题。',
    possibleReasons: [
      { reasonCode: 'TRAFFIC_015', reasonName: '无效浏览增加', confidence: 'high', evidenceNeeded: ['浏览来源', '转化率变化'], needHumanCheck: false },
      { reasonCode: 'CONVERSION_010', reasonName: '成交门槛变高', confidence: 'medium', evidenceNeeded: ['价格变化', '库存或配送状态'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R018',
    ruleName: '买家稳定但支付件数下降',
    primaryAnomalyType: 'customer_unit_price_drop',
    coreProblem: '单买家购买件数减少',
    businessMeaning: '买家规模稳定但件单减少，可能存在连带购买或单次购买数量下降。',
    possibleReasons: [
      { reasonCode: 'PRICE_004', reasonName: '连带购买减少', confidence: 'medium', evidenceNeeded: ['件单变化', '关联商品销售'], needHumanCheck: true },
      { reasonCode: 'TRANSACTION_006', reasonName: '热销多件商品缺货', confidence: 'medium', evidenceNeeded: ['库存状态', '热销商品支付件数'], needHumanCheck: true },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R019',
    ruleName: '销售额上升但转化下降',
    primaryAnomalyType: 'risk_fluctuation',
    coreProblem: '销售增长中存在转化效率下滑',
    businessMeaning: '销售额增长中存在转化效率下滑信号，需关注增长质量。',
    possibleReasons: [
      { reasonCode: 'RISK_001', reasonName: '高客单订单拉动销售额', confidence: 'medium', evidenceNeeded: ['客单价变化', '订单结构'], needHumanCheck: false },
      { reasonCode: 'RISK_002', reasonName: '新增流量质量偏低', confidence: 'medium', evidenceNeeded: ['访客来源', '转化率变化'], needHumanCheck: false },
    ],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R020',
    ruleName: '访客、买家、销售额同步下降',
    primaryAnomalyType: 'sales_decline',
    coreProblem: '核心经营链路同步走弱',
    businessMeaning: '流量、成交人群和销售规模同步走弱，是最高优先级经营异常。',
    possibleReasons: [
      { reasonCode: 'SALES_004', reasonName: '全链路经营下滑', confidence: 'high', evidenceNeeded: ['访客', '买家', '销售额趋势'], needHumanCheck: false },
      { reasonCode: 'TRAFFIC_016', reasonName: '平台或店铺流量资源明显减少', confidence: 'high', evidenceNeeded: ['曝光', '访客来源', '活动资源'], needHumanCheck: true },
    ],
    enabled: true,
  },
] satisfies BaseReasonTree[];
