import { createAlibaba1688Repository } from './alibaba1688RepositoryFactory.js';

export const alibaba1688ProductRepository = createAlibaba1688Repository({
  tableName: '"1688_products"',
  fields: [
    'id',
    'productCode',
    'productName',
    'categoryId',
    'productType',
    'material',
    'craft',
    'colorDescription',
    'sizeDescription',
    'listingTitle',
    'keywords',
    'sellingPoints',
    'detailDescription',
    'status',
    'listingStatus',
    'listingUrl',
    'storeId',
    'supplierId',
    'createdBy',
    'createdAt',
    'updatedAt',
    'remark',
  ],
  defaults: {
    productCode: '',
    productName: '',
    status: 'draft',
    listingStatus: 'not_listed',
  },
  searchColumns: ['product_code', 'product_name', 'listing_title', 'keywords'],
  filterColumns: {
    status: 'status',
    listingStatus: 'listing_status',
    categoryId: 'category_id',
    productType: 'product_type',
    storeId: 'store_id',
    supplierId: 'supplier_id',
    createdBy: 'created_by',
  },
});
