import type { BaseStrategyRule } from '../types';

export const TEMU_STRATEGY_LIBRARY = [
  {
    platform: 'TEMU',
    ruleCode: 'R001',
    ruleName: '访客数下降',
    primaryAnomalyType: 'traffic_drop',
    actions: [{
      actionCode: 'TRAFFIC_ACTION_001',
      actionName: '恢复核心商品流量',
      priority: 'high',
      ownerRole: 'operator',
      actionSteps: ['检查主推商品访客变化', '对比其他店铺是否同步下降', '检查活动是否结束', '检查价格竞争力', '优先恢复高流量商品曝光'],
      expectedEffect: '恢复店铺访客规模，降低销售额继续下滑风险。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R002',
    ruleName: '浏览量下降',
    primaryAnomalyType: 'traffic_quality_issue',
    actions: [{
      actionCode: 'TRAFFIC_ACTION_002',
      actionName: '提升商品浏览吸引力',
      priority: 'medium',
      ownerRole: 'operator',
      actionSteps: ['检查人均浏览量', '检查高访客低浏览商品', '优化主图和价格', '调整商品展示顺序', '补充更有吸引力的商品'],
      expectedEffect: '提升浏览深度和商品发现效率。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R003',
    ruleName: '支付买家数下降',
    primaryAnomalyType: 'transaction_decline',
    actions: [{
      actionCode: 'TRANSACTION_ACTION_001',
      actionName: '定位买家下降来源',
      priority: 'high',
      ownerRole: 'operator',
      actionSteps: ['判断是访客下降还是转化下降', '如果访客下降，优先恢复流量', '如果访客稳定，重点检查转化率和价格', '优先处理支付买家数下降最大的店铺'],
      expectedEffect: '明确成交买家减少原因并优先处理高影响店铺。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R004',
    ruleName: '支付转化率下降',
    primaryAnomalyType: 'conversion_drop',
    actions: [{
      actionCode: 'CONVERSION_ACTION_001',
      actionName: '修复高访客低转化商品',
      priority: 'high',
      ownerRole: 'operator',
      actionSteps: ['检查高访客低转化商品', '对比竞品价格', '优化主图、标题和商品卖点', '检查是否活动结束或近期调价', '必要时调整优惠'],
      expectedEffect: '提升访客成交效率。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R005',
    ruleName: '支付件数下降',
    primaryAnomalyType: 'transaction_decline',
    actions: [{
      actionCode: 'TRANSACTION_ACTION_002',
      actionName: '恢复支付件数',
      priority: 'high',
      ownerRole: 'operator',
      actionSteps: ['判断买家数是否同步下降', '检查件单量是否下降', '检查多件成交商品是否下滑', '优化组合款或多件购买商品', '排查库存或可售状态'],
      expectedEffect: '提升支付件数和商品成交规模。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R006',
    ruleName: '销售额下降',
    primaryAnomalyType: 'sales_decline',
    actions: [{
      actionCode: 'SALES_ACTION_001',
      actionName: '拆解销售额下降来源',
      priority: 'high',
      ownerRole: 'leader',
      actionSteps: ['拆解销售额下降来源', '判断是流量、转化、件数还是客单问题', '找出销售额下降最大的店铺或商品', '对高影响异常生成运营任务', '跟踪后续恢复效果'],
      expectedEffect: '锁定销售额下滑主因并推动恢复动作。',
      riskNote: '本配置仅定义策略，不自动生成任务。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R007',
    ruleName: '访客下降但转化稳定',
    primaryAnomalyType: 'traffic_drop',
    actions: [{
      actionCode: 'TRAFFIC_ACTION_003',
      actionName: '优先恢复访客规模',
      priority: 'high',
      ownerRole: 'operator',
      actionSteps: ['不要优先改详情页', '优先恢复商品曝光和访客', '检查活动和价格状态', '扩大高转化商品流量'],
      expectedEffect: '在转化稳定前提下恢复成交入口。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R008',
    ruleName: '访客稳定但转化下降',
    primaryAnomalyType: 'conversion_drop',
    actions: [{
      actionCode: 'CONVERSION_ACTION_002',
      actionName: '修复转化承接',
      priority: 'high',
      ownerRole: 'operator',
      actionSteps: ['优先检查价格和竞品', '优化高访客低转化商品', '调整主图、标题和卖点', '必要时调整优惠或活动'],
      expectedEffect: '提升稳定访客下的成交转化。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R009',
    ruleName: '浏览量上升但转化下降',
    primaryAnomalyType: 'traffic_quality_issue',
    actions: [{
      actionCode: 'TRAFFIC_ACTION_004',
      actionName: '处理高浏览低成交',
      priority: 'medium',
      ownerRole: 'operator',
      actionSteps: ['优化高浏览低成交商品', '检查价格和定制说明', '强化礼品属性和核心卖点', '降低购买决策成本'],
      expectedEffect: '把新增浏览转化为有效成交。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R010',
    ruleName: '访客上升但买家不升',
    primaryAnomalyType: 'conversion_drop',
    actions: [{
      actionCode: 'CONVERSION_ACTION_003',
      actionName: '校准新增流量转化',
      priority: 'medium',
      ownerRole: 'operator',
      actionSteps: ['不盲目继续放大流量', '检查新增访客来源和转化率', '优化高访客低买家商品', '检查主图是否吸引错人群'],
      expectedEffect: '提高新增访客的买家转化率。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R011',
    ruleName: '买家数下降且销售额下降',
    primaryAnomalyType: 'transaction_decline',
    actions: [{
      actionCode: 'TRANSACTION_ACTION_003',
      actionName: '恢复成交买家和销售额',
      priority: 'high',
      ownerRole: 'leader',
      actionSteps: ['同时拆解访客和转化变化', '优先排查主推成交商品', '检查活动结束和价格变化', '对下降最大的店铺生成任务'],
      expectedEffect: '优先止住成交人群和销售额同步下滑。',
      riskNote: '本配置仅定义策略，不自动生成任务。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R012',
    ruleName: '支付件数上升但销售额下降',
    primaryAnomalyType: 'customer_unit_price_drop',
    actions: [{
      actionCode: 'PRICE_ACTION_001',
      actionName: '优化商品成交结构',
      priority: 'medium',
      ownerRole: 'operator',
      actionSteps: ['检查件均价和客单价', '提升高客单商品曝光', '控制低价引流商品比例', '优化商品结构'],
      expectedEffect: '改善低价成交占比，恢复销售额质量。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R013',
    ruleName: '销售额下降但转化率上升',
    primaryAnomalyType: 'traffic_drop',
    actions: [{
      actionCode: 'TRAFFIC_ACTION_005',
      actionName: '恢复高转化流量',
      priority: 'high',
      ownerRole: 'operator',
      actionSteps: ['不要误判为整体经营变好', '优先恢复访客和曝光', '扩大高转化商品流量', '检查流量下降来源'],
      expectedEffect: '在转化改善基础上恢复销售额规模。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R014',
    ruleName: '销售额下降且访客下降',
    primaryAnomalyType: 'traffic_drop',
    actions: [{
      actionCode: 'TRAFFIC_ACTION_006',
      actionName: '优先修复流量端',
      priority: 'high',
      ownerRole: 'operator',
      actionSteps: ['优先恢复访客', '检查主推商品流量', '对比其他店铺是否同步下降', '不要优先改转化承接'],
      expectedEffect: '通过恢复访客改善销售额下滑。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R015',
    ruleName: '销售额下降且转化下降',
    primaryAnomalyType: 'conversion_drop',
    actions: [{
      actionCode: 'CONVERSION_ACTION_004',
      actionName: '优先修复转化问题',
      priority: 'high',
      ownerRole: 'leader',
      actionSteps: ['优先处理高访客低转化商品', '对比竞品价格', '优化主图、标题、卖点', '必要时调整优惠或价格策略'],
      expectedEffect: '提升转化并缓解销售额下降。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R016',
    ruleName: '访客稳定但浏览量下降',
    primaryAnomalyType: 'traffic_quality_issue',
    actions: [{
      actionCode: 'TRAFFIC_ACTION_007',
      actionName: '提升浏览深度',
      priority: 'medium',
      ownerRole: 'operator',
      actionSteps: ['检查人均浏览量', '优化主推商品排序和图片', '增加更有吸引力的商品展示', '检查商品价格竞争力'],
      expectedEffect: '提高稳定访客下的商品浏览深度。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R017',
    ruleName: '浏览量上升但买家下降',
    primaryAnomalyType: 'traffic_quality_issue',
    actions: [{
      actionCode: 'TRAFFIC_ACTION_008',
      actionName: '提升浏览到购买转化',
      priority: 'high',
      ownerRole: 'operator',
      actionSteps: ['优先优化高浏览低买家商品', '检查详情页和定制说明', '对比竞品价格', '强化信任感和礼品场景'],
      expectedEffect: '减少无效浏览，恢复支付买家数。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R018',
    ruleName: '买家稳定但支付件数下降',
    primaryAnomalyType: 'customer_unit_price_drop',
    actions: [{
      actionCode: 'PRICE_ACTION_002',
      actionName: '提升件单量',
      priority: 'medium',
      ownerRole: 'operator',
      actionSteps: ['检查件单量是否下降', '优化组合款和多件购买商品', '增加多件购买场景', '提升组合商品曝光'],
      expectedEffect: '提高单买家购买件数和成交结构质量。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R019',
    ruleName: '销售额上升但转化下降',
    primaryAnomalyType: 'risk_fluctuation',
    actions: [{
      actionCode: 'RISK_ACTION_001',
      actionName: '监控增长质量',
      priority: 'medium',
      ownerRole: 'operator',
      actionSteps: ['不要只看销售额增长', '继续观察转化率', '优化高访客低转化商品', '防止后续销售回落'],
      expectedEffect: '降低销售增长后的转化回落风险。',
    }],
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R020',
    ruleName: '访客、买家、销售额同步下降',
    primaryAnomalyType: 'sales_decline',
    actions: [{
      actionCode: 'SALES_ACTION_002',
      actionName: '处理全链路同步下滑',
      priority: 'high',
      ownerRole: 'leader',
      actionSteps: ['立即拆解流量和转化问题', '优先排查主推商品', '检查活动、价格、可售状态', '必须生成运营任务并跟踪恢复', '必须提示老板关注'],
      expectedEffect: '快速定位全链路下滑主因并推动高优先级恢复。',
      riskNote: '本配置仅定义策略，不自动生成任务或通知。',
    }],
    enabled: true,
  },
] satisfies BaseStrategyRule[];
