import type { BaseOperationRule } from '../types';

const DECLINE_CONDITION = '近7日均值较近30日均值下降 >=10% 为 watch，>=30% 为 warning，>=50% 为 critical';

export const TEMU_SINGLE_METRIC_RULES = [
  {
    platform: 'TEMU',
    ruleCode: 'R001',
    ruleName: '访客数下降',
    ruleType: 'single_metric',
    metricKeys: ['visitorCount'],
    anomalyLevel: 'warning',
    priority: 95,
    conditionDescription: DECLINE_CONDITION,
    businessMeaning: '店铺访客规模下降，后续存在销售额下滑风险。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R002',
    ruleName: '浏览量下降',
    ruleType: 'single_metric',
    metricKeys: ['viewCount'],
    anomalyLevel: 'watch',
    priority: 80,
    conditionDescription: DECLINE_CONDITION,
    businessMeaning: '商品曝光和浏览活跃度下降，可能影响后续访客与成交。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R003',
    ruleName: '支付买家数下降',
    ruleType: 'single_metric',
    metricKeys: ['payBuyerCount'],
    anomalyLevel: 'warning',
    priority: 100,
    conditionDescription: DECLINE_CONDITION,
    businessMeaning: '实际成交买家减少，销售规模存在直接下滑风险。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R004',
    ruleName: '支付转化率下降',
    ruleType: 'single_metric',
    metricKeys: ['payConversionRate'],
    anomalyLevel: 'warning',
    priority: 98,
    conditionDescription: DECLINE_CONDITION,
    businessMeaning: '流量成交效率下降，可能存在商品、价格或承接链路问题。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R005',
    ruleName: '支付件数下降',
    ruleType: 'single_metric',
    metricKeys: ['payItemCount'],
    anomalyLevel: 'warning',
    priority: 90,
    conditionDescription: DECLINE_CONDITION,
    businessMeaning: '订单商品件数减少，可能影响整体销售额和库存周转。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R006',
    ruleName: '销售额下降',
    ruleType: 'single_metric',
    metricKeys: ['salesAmount'],
    anomalyLevel: 'critical',
    priority: 100,
    conditionDescription: DECLINE_CONDITION,
    businessMeaning: '店铺销售规模下降，需要优先定位流量、转化或客单问题。',
    enabled: true,
  },
] satisfies BaseOperationRule[];
