import type { BaseOperationRule } from '../types';

const MULTI_METRIC_CONDITION = '近7日均值较近30日均值出现组合变化，核心指标下降 >=10% 为 watch，>=30% 为 warning，>=50% 为 critical';

export const TEMU_MULTI_METRIC_RULES = [
  {
    platform: 'TEMU',
    ruleCode: 'R007',
    ruleName: '访客下降但转化稳定',
    ruleType: 'multi_metric',
    metricKeys: ['visitorCount', 'payConversionRate'],
    anomalyLevel: 'warning',
    priority: 88,
    conditionDescription: '访客数下降，支付转化率基本稳定。',
    businessMeaning: '成交效率未明显恶化，销售压力主要来自流量规模减少。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R008',
    ruleName: '访客稳定但转化下降',
    ruleType: 'multi_metric',
    metricKeys: ['visitorCount', 'payConversionRate'],
    anomalyLevel: 'warning',
    priority: 96,
    conditionDescription: '访客数基本稳定，支付转化率下降。',
    businessMeaning: '流量规模尚可，但商品承接或购买决策效率下降。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R009',
    ruleName: '浏览量上升但转化下降',
    ruleType: 'multi_metric',
    metricKeys: ['viewCount', 'payConversionRate'],
    anomalyLevel: 'warning',
    priority: 92,
    conditionDescription: '浏览量上升，支付转化率下降。',
    businessMeaning: '曝光或浏览增加但成交效率变差，可能存在流量质量或商品承接问题。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R010',
    ruleName: '访客上升但买家不升',
    ruleType: 'multi_metric',
    metricKeys: ['visitorCount', 'payBuyerCount'],
    anomalyLevel: 'watch',
    priority: 82,
    conditionDescription: '访客数上升，支付买家数未同步上升。',
    businessMeaning: '新增流量未有效转化为买家，需要关注流量质量和转化链路。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R011',
    ruleName: '买家数下降且销售额下降',
    ruleType: 'multi_metric',
    metricKeys: ['payBuyerCount', 'salesAmount'],
    anomalyLevel: 'critical',
    priority: 100,
    conditionDescription: MULTI_METRIC_CONDITION,
    businessMeaning: '成交人群减少并带动销售额下滑，是高优先级经营风险。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R012',
    ruleName: '支付件数上升但销售额下降',
    ruleType: 'multi_metric',
    metricKeys: ['payItemCount', 'salesAmount'],
    anomalyLevel: 'warning',
    priority: 90,
    conditionDescription: '支付件数上升，销售额下降。',
    businessMeaning: '销量件数提升但销售额下降，可能存在均价下降或低价商品占比提升。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R013',
    ruleName: '销售额下降但转化率上升',
    ruleType: 'multi_metric',
    metricKeys: ['salesAmount', 'payConversionRate'],
    anomalyLevel: 'warning',
    priority: 86,
    conditionDescription: '销售额下降，支付转化率上升。',
    businessMeaning: '成交效率改善但销售额仍下降，需关注流量规模、买家数或客单变化。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R014',
    ruleName: '销售额下降且访客下降',
    ruleType: 'multi_metric',
    metricKeys: ['salesAmount', 'visitorCount'],
    anomalyLevel: 'critical',
    priority: 98,
    conditionDescription: MULTI_METRIC_CONDITION,
    businessMeaning: '销售额下滑与访客减少同步出现，流量端可能是核心影响因素。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R015',
    ruleName: '销售额下降且转化下降',
    ruleType: 'multi_metric',
    metricKeys: ['salesAmount', 'payConversionRate'],
    anomalyLevel: 'critical',
    priority: 99,
    conditionDescription: MULTI_METRIC_CONDITION,
    businessMeaning: '销售额和成交效率同步下滑，需优先排查商品、价格和转化链路。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R016',
    ruleName: '访客稳定但浏览量下降',
    ruleType: 'multi_metric',
    metricKeys: ['visitorCount', 'viewCount'],
    anomalyLevel: 'watch',
    priority: 72,
    conditionDescription: '访客数基本稳定，浏览量下降。',
    businessMeaning: '人均浏览深度下降，可能影响商品发现和后续成交。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R017',
    ruleName: '浏览量上升但买家下降',
    ruleType: 'multi_metric',
    metricKeys: ['viewCount', 'payBuyerCount'],
    anomalyLevel: 'warning',
    priority: 91,
    conditionDescription: '浏览量上升，支付买家数下降。',
    businessMeaning: '浏览热度未转化为成交买家，可能存在购买意愿或商品竞争力问题。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R018',
    ruleName: '买家稳定但支付件数下降',
    ruleType: 'multi_metric',
    metricKeys: ['payBuyerCount', 'payItemCount'],
    anomalyLevel: 'watch',
    priority: 78,
    conditionDescription: '支付买家数基本稳定，支付件数下降。',
    businessMeaning: '买家规模稳定但件单减少，可能存在连带购买或单次购买数量下降。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R019',
    ruleName: '销售额上升但转化下降',
    ruleType: 'multi_metric',
    metricKeys: ['salesAmount', 'payConversionRate'],
    anomalyLevel: 'watch',
    priority: 70,
    conditionDescription: '销售额上升，支付转化率下降。',
    businessMeaning: '销售额增长中存在转化效率下滑信号，需关注增长质量。',
    enabled: true,
  },
  {
    platform: 'TEMU',
    ruleCode: 'R020',
    ruleName: '访客、买家、销售额同步下降',
    ruleType: 'multi_metric',
    metricKeys: ['visitorCount', 'payBuyerCount', 'salesAmount'],
    anomalyLevel: 'critical',
    priority: 100,
    conditionDescription: MULTI_METRIC_CONDITION,
    businessMeaning: '流量、成交人群和销售规模同步走弱，是最高优先级经营异常。',
    enabled: true,
  },
] satisfies BaseOperationRule[];
