export const menuKeys = {
  dashboard: 'dashboard',
  dataCenter: 'data-center',
  orderSalesImport: 'order-sales-import',
  trafficConversionImport: 'traffic-conversion-import',
  dataManagement: 'data-management',
  dataBackup: 'data-backup',
  storeData: 'store-data',
  operationData: 'operation-data',
  analysisResults: 'analysis-results',
  storeManagement: 'store-management',
  operatorManagement: 'operator-management',
  accountManagement: 'account-management',
  newProductCenter: 'new-product-center',
  newProductBossDashboard: 'new-product-boss-dashboard',
  newProductWorkbench: 'new-product-workbench',
  newProductOperatorDashboard: 'new-product-operator-dashboard',
  newProductProducts: 'new-product-products',
  newProductAdRecommendations: 'new-product-ad-recommendations',
  temuProductInfoImport: 'temu-product-info-import',
  temuAdReportImport: 'temu-ad-report-import',
  businessAnalysis: 'business-analysis',
  businessAnalysisCenter: 'business-analysis-center',
  business1688Center: '1688-business-center',
  business1688Products: '1688-products',
  business1688ListingTasks: '1688-listing-tasks',
  business1688Images: '1688-images',
  business1688Suppliers: '1688-suppliers',
  business1688Settings: '1688-settings',
  storeBusinessCenter: 'store-business-center',
  operatorAnalysisCenter: 'operator-analysis-center',
  operationDiagnosis: 'operation-diagnosis',
  aiOperationAnalysis: 'ai-operation-analysis',
  operatorPerformance: 'operator-performance',
  growthOpportunities: 'growth-opportunities',
  operationLoop: 'operation-loop',
  operationTools: 'operation-tools',
  operationTasks: 'operation-tasks',
  taskSuggestions: 'task-suggestions',
  aiImagePromptCenter: 'ai-image-prompt-center',
  ruleCenter: 'rule-center',
  kpiRules: 'kpi-rules',
  rankingRules: 'ranking-rules',
  businessRules: 'business-rules',
  anomalyRules: 'anomaly-rules',
  dataSource: 'data-source',
  dataSourceConfig: 'data-source-config',
  salaryPerformance: 'salary-performance',
  salaryEmployees: 'salary-employees',
  salaryPeriods: 'salary-periods',
  salaryImportTemplates: 'salary-import-templates',
  salaryAttendanceImport: 'salary-attendance-import',
  salaryPieceworkImport: 'salary-piecework-import',
  salaryDetails: 'salary-details',
  salaryPlan: 'salary-plan',
  financeDetailImport: 'finance-detail-import',
  operationSalaryStatistics: 'operation-salary-statistics',
} as const;

export type MenuKey = typeof menuKeys[keyof typeof menuKeys];

export const menuGroups: { key: MenuKey; label: string; children: { key: MenuKey; label: string }[] }[] = [
  { key: menuKeys.dashboard, label: '我的工作台', children: [{ key: menuKeys.dashboard, label: '我的工作台' }] },
  {
    key: menuKeys.dataCenter,
    label: '数据中心',
    children: [
      { key: menuKeys.orderSalesImport, label: '订单数据导入' },
      { key: menuKeys.trafficConversionImport, label: '流量转化导入' },
      { key: menuKeys.temuProductInfoImport, label: '商品信息导入' },
      { key: menuKeys.temuAdReportImport, label: '广告数据导入' },
      { key: menuKeys.dataManagement, label: '数据管理' },
      { key: menuKeys.dataBackup, label: '数据备份' },
    ],
  },
  {
    key: menuKeys.newProductCenter,
    label: '新品中心',
    children: [
      { key: menuKeys.newProductBossDashboard, label: '老板总览' },
      { key: menuKeys.newProductWorkbench, label: '新品工作台' },
      { key: menuKeys.newProductAdRecommendations, label: '广告策略中心' },
    ],
  },
  {
    key: menuKeys.storeManagement,
    label: '店铺管理',
    children: [{ key: menuKeys.storeManagement, label: '店铺管理' }],
  },
  {
    key: menuKeys.operatorManagement,
    label: '运营管理',
    children: [{ key: menuKeys.operatorManagement, label: '运营管理' }],
  },
  {
    key: menuKeys.accountManagement,
    label: '账号管理',
    children: [{ key: menuKeys.accountManagement, label: '账号管理' }],
  },
  {
    key: menuKeys.businessAnalysis,
    label: '经营分析',
    children: [
      { key: menuKeys.storeBusinessCenter, label: '店铺经营中心' },
      { key: menuKeys.operatorAnalysisCenter, label: '运营分析中心' },
      { key: menuKeys.businessAnalysisCenter, label: '风险诊断中心' },
      { key: menuKeys.operationDiagnosis, label: '异常结果中心' },
      { key: menuKeys.aiOperationAnalysis, label: 'AI运营分析' },
      { key: menuKeys.growthOpportunities, label: '增长机会' },
    ],
  },
  {
    key: menuKeys.operationLoop,
    label: '运营闭环',
    children: [
      { key: menuKeys.operationTasks, label: '运营任务中心' },
      { key: menuKeys.taskSuggestions, label: '处理建议模板' },
    ],
  },
  {
    key: menuKeys.business1688Center,
    label: '1688业务',
    children: [
      { key: menuKeys.business1688Products, label: '产品库' },
      { key: menuKeys.business1688ListingTasks, label: '上架任务' },
      { key: menuKeys.business1688Images, label: '图片素材' },
      { key: menuKeys.business1688Suppliers, label: '供应商管理' },
      { key: menuKeys.business1688Settings, label: '1688设置' },
    ],
  },
  {
    key: menuKeys.operationTools,
    label: '运营工具',
    children: [
      { key: menuKeys.aiImagePromptCenter, label: 'AI图片提示词中心' },
    ],
  },
  {
    key: menuKeys.ruleCenter,
    label: '规则中心',
    children: [
      { key: menuKeys.kpiRules, label: 'KPI规则' },
      { key: menuKeys.rankingRules, label: '排名规则' },
      { key: menuKeys.businessRules, label: '经营规则' },
      { key: menuKeys.anomalyRules, label: '异常规则' },
    ],
  },
  {
    key: menuKeys.dataSource,
    label: '数据源',
    children: [{ key: menuKeys.dataSourceConfig, label: '数据源配置' }],
  },
  {
    key: menuKeys.salaryPerformance,
    label: '薪资绩效',
    children: [
      { key: menuKeys.salaryEmployees, label: '员工档案' },
      { key: menuKeys.salaryPeriods, label: '工资周期' },
      { key: menuKeys.salaryImportTemplates, label: '导入模板配置' },
      { key: menuKeys.salaryAttendanceImport, label: '打卡记录导入' },
      { key: menuKeys.salaryPieceworkImport, label: '计件工资导入' },
      { key: menuKeys.financeDetailImport, label: '财务明细导入' },
      { key: menuKeys.operationSalaryStatistics, label: '运营工资统计' },
      { key: menuKeys.salaryDetails, label: '工资明细中心' },
      { key: menuKeys.salaryPlan, label: '薪资系统规划' },
    ],
  },
];

export const menuOptions = menuGroups.flatMap((group) => group.children);
export const allMenuKeys = Array.from(new Set([
  ...menuGroups.map((group) => group.key),
  ...menuOptions.map((item) => item.key),
]));
