import { menuKeys, type MenuKey } from './menuKeys';

export interface AdminRoute {
  path: string;
  label: string;
  group: string;
  description: string;
  menuKey: MenuKey;
  parentMenuKey?: MenuKey;
  menuSection?: string;
  isPlaceholder?: boolean;
  hideInMenu?: boolean;
}

export const adminRoutes: AdminRoute[] = [
  {
    path: '/admin',
    menuKey: menuKeys.dashboard,
    label: '我的工作台',
    group: '总览',
    description: '后台管理入口，汇总导入、数据、规则和数据源状态。',
  },
  {
    path: '/admin/import',
    menuKey: menuKeys.orderSalesImport,
    parentMenuKey: menuKeys.dataCenter,
    label: '订单销售导入',
    group: '数据',
    menuSection: '数据导入',
    description: '上传订单销售 Excel，生成大屏销售数据。',
  },
  {
    path: '/admin/traffic-import',
    menuKey: menuKeys.trafficConversionImport,
    parentMenuKey: menuKeys.dataCenter,
    label: '流量转化导入',
    group: '数据',
    menuSection: '数据导入',
    description: '上传店铺每日流量转化 Excel。',
  },
  {
    path: '/admin/temu-product-info-import',
    menuKey: menuKeys.temuProductInfoImport,
    parentMenuKey: menuKeys.dataCenter,
    label: '商品信息导入',
    group: '数据',
    menuSection: '数据导入',
    description: '导入 TEMU 商品和 SKU 信息，写入 PostgreSQL 商品基础表。',
  },
  {
    path: '/admin/temu-ad-report-import',
    menuKey: menuKeys.temuAdReportImport,
    parentMenuKey: menuKeys.dataCenter,
    label: 'TEMU广告数据导入',
    group: '数据',
    menuSection: '数据导入',
    description: '导入 TEMU 商品推广报表，写入 PostgreSQL 广告日报表。',
  },
  {
    path: '/admin/effective-new-listings',
    menuKey: menuKeys.effectiveNewListings,
    parentMenuKey: menuKeys.dataCenter,
    label: '有效上新录入',
    group: '数据',
    menuSection: '数据导入',
    description: '手动登记店铺有效上新 SKC，驱动首页有效上新排名。',
  },
  {
    path: '/admin/data',
    menuKey: menuKeys.dataManagement,
    parentMenuKey: menuKeys.dataCenter,
    label: '数据管理',
    group: '数据',
    menuSection: '数据源',
    description: '查看和修正大屏展示数据。',
  },
  {
    path: '/admin/data-backup',
    menuKey: menuKeys.dataBackup,
    parentMenuKey: menuKeys.dataCenter,
    label: '数据备份',
    group: '数据',
    menuSection: '数据源',
    description: '一键备份 data 目录下的重要 JSON 文件。',
  },
  {
    path: '/admin/stores',
    menuKey: menuKeys.storeManagement,
    label: '店铺管理',
    group: '基础资料',
    description: '维护店铺名称、平台、站点、状态、分组和备注。',
  },
  {
    path: '/admin/operators',
    menuKey: menuKeys.operatorManagement,
    label: '运营管理',
    group: '基础资料',
    description: '维护运营人员和店铺-运营关系。',
  },
  {
    path: '/admin/accounts',
    menuKey: menuKeys.accountManagement,
    label: '账号管理',
    group: '基础资料',
    description: '维护后台登录账号、角色和授权店铺。',
  },
  {
    path: '/admin/tasks',
    menuKey: menuKeys.operationTasks,
    parentMenuKey: menuKeys.operationLoop,
    label: '运营任务中心',
    group: '运营闭环',
    description: '承接预警和增长机会，记录负责人、状态、截止日期和处理结果。',
  },
  {
    path: '/admin/task-suggestions',
    menuKey: menuKeys.taskSuggestions,
    parentMenuKey: menuKeys.operationLoop,
    label: '处理建议模板',
    group: '运营闭环',
    description: '维护流量、转化、成交和增长机会的运营处理建议模板。',
  },
  {
    path: '/admin/ai-image-prompts',
    menuKey: menuKeys.aiImagePromptCenter,
    parentMenuKey: menuKeys.operationTools,
    label: 'AI图片提示词中心',
    group: '运营工具',
    description: '根据平台、图片用途和产品信息生成标准化图片提示词。',
  },
  {
    path: '/admin/config/kpi',
    menuKey: menuKeys.kpiRules,
    parentMenuKey: menuKeys.ruleCenter,
    label: 'KPI规则',
    group: '规则中心',
    description: '维护核心指标口径。',
  },
  {
    path: '/admin/config/ranking',
    menuKey: menuKeys.rankingRules,
    parentMenuKey: menuKeys.ruleCenter,
    label: '排名规则',
    group: '规则中心',
    description: '维护排名口径。',
  },
  {
    path: '/admin/config/warnings',
    menuKey: menuKeys.businessRules,
    parentMenuKey: menuKeys.ruleCenter,
    label: '经营规则',
    group: '规则中心',
    description: '维护风险预警和增长机会规则。',
  },
  {
    path: '/admin/config/anomaly-rules',
    menuKey: menuKeys.anomalyRules,
    parentMenuKey: menuKeys.ruleCenter,
    isPlaceholder: true,
    label: '异常规则',
    group: '规则中心',
    description: '异常规则页面建设中。',
  },
  {
    path: '/admin/1688-business/products',
    menuKey: menuKeys.business1688Products,
    parentMenuKey: menuKeys.business1688Center,
    label: '产品库',
    group: '1688业务',
    description: '维护 1688 产品资料和 SKU，图片、供应商和上架任务后续分模块处理。',
  },
  {
    path: '/admin/1688-business/products/new',
    menuKey: menuKeys.business1688Products,
    parentMenuKey: menuKeys.business1688Center,
    label: '新增商品',
    group: '1688业务',
    description: '分步骤新增 1688 商品资料、SKU、图片路径和上架基础信息。',
    hideInMenu: true,
  },
  {
    path: '/admin/1688-business/listing-tasks',
    menuKey: menuKeys.business1688ListingTasks,
    parentMenuKey: menuKeys.business1688Center,
    label: '上架任务',
    group: '1688业务',
    description: '承接产品库生成的人工上架任务，回填 1688 商品链接。',
  },
  {
    path: '/admin/1688-business/images',
    menuKey: menuKeys.business1688Images,
    parentMenuKey: menuKeys.business1688Center,
    label: '图片素材',
    group: '1688业务',
    description: '维护产品图片、SKU 图片和详情页素材的关联关系。',
  },
  {
    path: '/admin/1688-business/suppliers',
    menuKey: menuKeys.business1688Suppliers,
    parentMenuKey: menuKeys.business1688Center,
    label: '供应商管理',
    group: '1688业务',
    description: '维护 1688 供应商基础信息，并关联产品库。',
  },
  {
    path: '/admin/1688-business/settings',
    menuKey: menuKeys.business1688Settings,
    parentMenuKey: menuKeys.business1688Center,
    label: '1688设置',
    group: '1688业务',
    description: '维护 1688 店铺映射和产品分类、材质、工艺、颜色、尺寸单位、发货地、发货时间、运费模板等基础配置。',
  },
  {
    path: '/admin/store-business',
    menuKey: menuKeys.storeBusinessCenter,
    parentMenuKey: menuKeys.businessAnalysis,
    label: '店铺经营中心',
    group: '经营分析',
    description: '按店铺维度查看销售、流量、转化、风险和增长机会趋势。',
  },
  {
    path: '/new-product-center/boss-dashboard',
    menuKey: menuKeys.newProductBossDashboard,
    parentMenuKey: menuKeys.newProductCenter,
    label: '老板总览',
    group: '新品中心',
    description: '查看 TEMU 新品上架、出单、广告和运营排名。',
  },
  {
    path: '/new-product-center/operator-dashboard',
    menuKey: menuKeys.newProductOperatorDashboard,
    parentMenuKey: menuKeys.newProductCenter,
    label: '运营首页',
    group: '新品中心',
    description: '查看当前运营负责店铺的新品表现和待处理建议。',
  },
  {
    path: '/new-product-center/products',
    menuKey: menuKeys.newProductProducts,
    parentMenuKey: menuKeys.newProductCenter,
    label: '新品列表',
    group: '新品中心',
    description: '按店铺、运营、上架时间、广告、出单和标签筛选新品。',
  },
  {
    path: '/new-product-center/ad-recommendations',
    menuKey: menuKeys.newProductAdRecommendations,
    parentMenuKey: menuKeys.newProductCenter,
    label: '广告建议中心',
    group: '新品中心',
    description: '查看并处理新品广告建议。',
  },
  {
    path: '/new-product-center/products/detail',
    menuKey: menuKeys.newProductProducts,
    parentMenuKey: menuKeys.newProductCenter,
    label: '商品详情',
    group: '新品中心',
    description: '查看商品基础信息、趋势、建议历史和时间线。',
    hideInMenu: true,
  },
  {
    path: '/admin/operator-analysis',
    menuKey: menuKeys.operatorAnalysisCenter,
    parentMenuKey: menuKeys.businessAnalysis,
    label: '运营分析中心',
    group: '经营分析',
    description: '按运营人员维度查看负责店铺、风险、增长和任务处理效果。',
  },
  {
    path: '/admin/warning-results',
    menuKey: menuKeys.businessAnalysisCenter,
    parentMenuKey: menuKeys.businessAnalysis,
    label: '风险诊断中心',
    group: '经营分析',
    description: '查看风险预警、增长机会和详细分析列表。',
  },
  {
    path: '/admin/operation-diagnosis',
    menuKey: menuKeys.operationDiagnosis,
    parentMenuKey: menuKeys.businessAnalysis,
    label: '异常结果中心',
    group: '经营分析',
    description: '查看平台无关的运营异常诊断结果、规则树判断和解决方案。',
  },
  {
    path: '/admin/ai-operation-analysis',
    menuKey: menuKeys.aiOperationAnalysis,
    parentMenuKey: menuKeys.businessAnalysis,
    label: 'AI运营分析',
    group: '经营分析',
    description: 'AI运营分析页面建设中。',
    isPlaceholder: true,
  },
  {
    path: '/admin/operator-performance',
    menuKey: menuKeys.operatorAnalysisCenter,
    parentMenuKey: menuKeys.businessAnalysis,
    label: '运营业绩分析',
    group: '经营分析',
    description: '查看运营负责店铺的业绩汇总和风险增长分析。',
  },
  {
    path: '/admin/growth-opportunities',
    menuKey: menuKeys.growthOpportunities,
    parentMenuKey: menuKeys.businessAnalysis,
    label: '增长机会',
    group: '经营分析',
    description: '增长机会页面建设中。',
    isPlaceholder: true,
  },
  {
    path: '/admin/data-sources',
    menuKey: menuKeys.dataSourceConfig,
    parentMenuKey: menuKeys.dataSource,
    label: '数据源配置',
    group: '数据源',
    description: '配置 Excel、店小秘、TEMU后台、飞书和 ERP 数据源。',
  },
  {
    path: '/admin/salary/employees',
    menuKey: menuKeys.salaryEmployees,
    parentMenuKey: menuKeys.salaryPerformance,
    label: '员工档案',
    group: '薪资绩效',
    description: '预留计时、计件、运营、管理和月薪员工基础档案。',
  },
  {
    path: '/admin/salary/periods',
    menuKey: menuKeys.salaryPeriods,
    parentMenuKey: menuKeys.salaryPerformance,
    label: '工资周期',
    group: '薪资绩效',
    description: '预留月度工资周期和 draft / calculated / locked 状态。',
  },
  {
    path: '/admin/salary/import-templates',
    menuKey: menuKeys.salaryImportTemplates,
    parentMenuKey: menuKeys.salaryPerformance,
    label: '导入模板配置',
    group: '薪资绩效',
    description: '预留打卡和计件 Excel 字段映射配置。',
  },
  {
    path: '/admin/salary/attendance-import',
    menuKey: menuKeys.salaryAttendanceImport,
    parentMenuKey: menuKeys.salaryPerformance,
    label: '打卡记录导入',
    group: '薪资绩效',
    description: '导入真实打卡矩阵，保存考勤事实，不做工资计算。',
  },
  {
    path: '/admin/salary/piecework-import',
    menuKey: menuKeys.salaryPieceworkImport,
    parentMenuKey: menuKeys.salaryPerformance,
    label: '计件工资导入',
    group: '薪资绩效',
    description: '导入计件明细，保存计件事实，不生成工资单。',
  },
  {
    path: '/admin/salary/finance-detail-import',
    menuKey: menuKeys.financeDetailImport,
    parentMenuKey: menuKeys.salaryPerformance,
    label: '财务明细导入',
    group: '薪资绩效',
    description: '按平台、店铺和月份导入财务明细，生成运营工资核算所需的店铺月度汇总。',
  },
  {
    path: '/admin/salary/operator-salary-statistics',
    menuKey: menuKeys.operationSalaryStatistics,
    parentMenuKey: menuKeys.salaryPerformance,
    label: '运营工资统计',
    group: '薪资绩效',
    description: '根据员工档案基本工资、运营店铺关系和财务明细汇总计算运营工资。',
  },
  {
    path: '/admin/salary/details',
    menuKey: menuKeys.salaryDetails,
    parentMenuKey: menuKeys.salaryPerformance,
    label: '工资明细中心',
    group: '薪资绩效',
    description: '汇总展示计时、计件、月薪和管理工资明细。',
  },
  {
    path: '/admin/salary/plan',
    menuKey: menuKeys.salaryPlan,
    parentMenuKey: menuKeys.salaryPerformance,
    label: '薪资系统规划',
    group: '薪资绩效',
    description: '展示计时、计件、管理人员工资来源和后续模块路径。',
  },
];
